  - name: copying the mongorepo
    ansible.builtin.copy:
      src: mongo.repo 
      dest: /etc/yum.repos.d/mongod.repo

  - name: installing mongodb server
    ansible.builtin.dnf:
      name: mongodb-org
      state: present

  - name: starting and enabling service 
    ansible.builtin.service:
      name: mongod
      state: started
      enabled: yes

  - name: allowing remote connection
    ansible.builtin.replace:
      path: /etc/mongod.conf
      regexp: "127.0.0.1"
      replace: "0.0.0.0"




  - name: restarting service
    ansible.builtin.service:
      name: mongod
      state: restarted