  - name: creating folder
    ansible.builtin.file:
      path: /app
      state: directory

  - name: downloading content for "{{ component }}"
    ansible.builtin.get_url: 
      url: "https://roboshop-artifacts.s3.amazonaws.com/{{ component }}-v3.zip"
      dest: "/tmp/{{ component }}.zip"

  - name: creating system user
    ansible.builtin.user:
      name: roboshop
      shell: /sbin/nologin
      home: /app
      system: true

  - name: extract code
    ansible.builtin.unarchive:
      src: "/tmp/{{ component }}.zip"
      dest: /app
      remote_src: yes