- name: app setup
  include_role:
    name: common
    tasks_from: app-setup

- name: go lang setup
  include_role:
    name: common
    tasks_from: go-setup

- name: systemd setup
  include_role:
    name: common
    tasks_from: systemd-setup