- name: installing mysql server
  ansible.builtin.dnf:
    name: mysql-server
    state: present

- name: starting and enable service
  ansible.builtin.service:
    name: mysqld
    state: started
    enabled: yes

- name: setting passwd root
  ansible.builtin.command: mysql_secure_installation --set-root-pass RoboShop@1