- name: app setup
  include_role:
    name: common
    tasks_from: app-setup

- name: copy payment.ini
  ansible.builtin.copy:
    src: payment.ini
    dest: /app

- name: python depedencies
  include_role:
    name: common
    tasks_from: python-setup

- name: systemd start
  include_role:
    name: common
    tasks_from: systemd-setup