- name: installing golang
  ansible.builtin.dnf:
    name: golang
    state: present

- name: Initialize Go module
  ansible.builtin.command: go mod init dispatch
  args:
    chdir: /app
  when: not ansible_check_mode

- name: Download dependencies
  ansible.builtin.command: go get
  args:
    chdir: /app

- name: Build Go project
  ansible.builtin.command: go build
  args:
    chdir: /app