- name: disable  redis 
  ansible.builtin.command: dnf module disable redis -y

- name: enable redis 7
  ansible.builtin.command: dnf module enable redis:7 -y


- name: installing redis server
  ansible.builtin.dnf:
    name: redis
    state: present

- name: starting and enabling service 
  ansible.builtin.service:
    name: redis
    state: started
    enabled: yes

- name: allowing remote connection
  ansible.builtin.replace:
    path: /etc/redis/redis.conf
    regexp: "127.0.0.1"
    replace: "0.0.0.0"

- name: allowing redis protective mode
  ansible.builtin.lineinfile:
    path: /etc/redis/redis.conf
    regexp: "protected-mode"
    line: protected-mode no



- name: restarting service
  ansible.builtin.service:
    name: redis
    state: restarted